import { useListIntros, getListIntrosQueryKey } from '@workspace/api-client-react';
import type { IntroSuggestion } from '@workspace/api-client-react';
import { Link } from 'wouter';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ArrowLeftRight, Copy, RefreshCw, Sparkles, Users } from 'lucide-react';
import { toast } from 'sonner';

// Suggestions are generated by an LLM on each fetch, so keep them fresh for a
// few minutes rather than regenerating every time the tab is opened.
const FIVE_MINUTES = 5 * 60 * 1000;

function Party({ id, name, role, company }: IntroSuggestion['personA']) {
  const line = [role, company].filter(Boolean).join(' at ');
  return (
    <Link href={`/people/${id}`} className="group min-w-0">
      <p className="font-medium text-foreground truncate group-hover:underline underline-offset-4">
        {name}
      </p>
      {line && <p className="text-xs text-muted-foreground truncate">{line}</p>}
    </Link>
  );
}

function IntroCard({ intro }: { intro: IntroSuggestion }) {
  const copyDraft = async () => {
    try {
      await navigator.clipboard.writeText(intro.draftIntro);
      toast.success('Intro copied to clipboard.');
    } catch {
      toast.error('Could not copy. You can select the text manually.');
    }
  };

  return (
    <Card>
      <CardContent className="p-5 space-y-4">
        <div className="flex items-start justify-between gap-3">
          <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 min-w-0 flex-1">
            <Party {...intro.personA} />
            <ArrowLeftRight className="w-4 h-4 text-muted-foreground shrink-0" />
            <Party {...intro.personB} />
          </div>
          <Badge variant="secondary" className="shrink-0 tabular-nums">
            {intro.score} match
          </Badge>
        </div>

        {intro.rationale && (
          <p className="text-sm text-foreground leading-relaxed">{intro.rationale}</p>
        )}

        {intro.draftIntro && (
          <div className="rounded-lg bg-muted/50 border border-dashed p-3 space-y-3">
            <p className="text-sm text-muted-foreground italic leading-relaxed">
              {intro.draftIntro}
            </p>
            <Button variant="outline" size="sm" onClick={copyDraft}>
              <Copy className="w-3.5 h-3.5 mr-2" />
              Copy intro
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

export default function Intros() {
  const {
    data: intros = [],
    isLoading,
    isFetching,
    isError,
    refetch,
  } = useListIntros({
    query: {
      queryKey: getListIntrosQueryKey(),
      staleTime: FIVE_MINUTES,
      gcTime: FIVE_MINUTES,
    },
  });

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-serif font-bold text-foreground">Warm intros</h1>
          <p className="text-muted-foreground mt-1">
            People in your network who could help each other.
          </p>
        </div>
        <Button
          variant="outline"
          className="shrink-0 rounded-full"
          onClick={() => refetch()}
          disabled={isFetching}
        >
          <RefreshCw className={`w-4 h-4 mr-2 ${isFetching ? 'animate-spin' : ''}`} />
          {isFetching ? 'Connecting the dots...' : 'Find new intros'}
        </Button>
      </div>

      {isLoading ? (
        <div className="min-h-[40vh] flex flex-col items-center justify-center text-center gap-4">
          <Sparkles className="w-8 h-8 text-primary animate-pulse" />
          <p className="text-lg font-serif text-foreground">Connecting the dots...</p>
          <p className="text-sm text-muted-foreground max-w-xs">
            Orbit is looking for people who could help each other.
          </p>
        </div>
      ) : isError ? (
        <Card className="border-dashed">
          <CardContent className="p-6 text-center space-y-3">
            <p className="text-sm text-muted-foreground">
              Couldn't generate introductions right now.
            </p>
            <Button variant="outline" size="sm" onClick={() => refetch()}>
              Try again
            </Button>
          </CardContent>
        </Card>
      ) : intros.length === 0 ? (
        <div className="min-h-[40vh] flex flex-col items-center justify-center text-center gap-3">
          <Users className="w-8 h-8 text-muted-foreground" />
          <p className="text-lg font-serif text-foreground">No warm intros yet</p>
          <p className="text-sm text-muted-foreground max-w-sm">
            Capture a few more people, especially what they're working on or looking for, and
            Orbit will start spotting connections worth making.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {intros.map((intro) => (
            <IntroCard
              key={`${intro.personA.id}-${intro.personB.id}`}
              intro={intro}
            />
          ))}
        </div>
      )}
    </div>
  );
}
